services:
  db:
    image: postgres:17-alpine
    container_name: telepathie_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: development
    container_name: telepathie_api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  front:
    build:
      context: ../telepathie_front
      target: development
    container_name: telepathie_front
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    env_file:
      - ../telepathie_front/.env
    volumes:
      - ../telepathie_front:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_data: